baseURL = "https://doi-t.github.io/"
languageCode = "en-us"
title = "cat tech_notes | grep \"$relevant, I guess.\""
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
pygmentsCodefences = true
pygmentsUseClasses = true

[permalinks]
  posts = "/:year/:month/:day/:title/"

[params]
  author = "Toshiya Doi"
  description = "Random tech notes as an output and practice writing English."

[menu]
  [[menu.nav]]
  name = "posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "about"
  url = "/about/"
  weight = 2
  [[menu.nav]]
  name = "rss"
  url = "/index.xml"
  weight = 3
