baseURL = "https://doi-t.net/"
languageCode = "en-us"
title = "cat tech_notes | grep \"$relevant, I guess.\""
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
pygmentsCodefences = true
pygmentsUseClasses = true
googleAnalytics ="UA-48136686-2"

[permalinks]
  posts = "/:year/:month/:day/:title/"

[params]
  author = "Toshiya Doi"
  description = "Random tech notes as an output and practice writing English."
  githubLink = "https://github.com/doi-t"
  twitterLink = "https://twitter.com/DDDDoi"
  japaneseBlogLink = "http://doi-t.hatenablog.com"

[menu]
  [[menu.nav]]
  name = "posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "about"
  url = "/about/"
  weight = 2
  [[menu.nav]]
  name = "rss"
  url = "/index.xml"
  weight = 3
